AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CloudWatchIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: "CloudWatchLoggingRole"
      # Trust Policy: Allows EC2 instances to assume this role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      # Permissions Policy: Grants access to CloudWatch Logs and Metrics
      Policies:
        - PolicyName: "CloudWatchAccessPolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'logs:DescribeLogStreams'
                  - 'cloudwatch:PutMetricData'
                Resource: '*'
